name: Docker Build and Push to ACR

on:
  push:
    branches:
      - main  # Trigger on the main branch

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and run tests
      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Run tests for Node.js
        run: |
          npm test

      - name: Docker Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/myapp
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Docker Image to ACR
        run: |
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/myapp
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Logout from Docker
        run: docker logout

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: dockerize-and-push
  #   steps:
  #     # Checkout the repository
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     # Set up Azure CLI
  #     - name: Install Azure CLI
  #       run: |
  #         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  #     # Log in to Azure using service principal credentials
  #     - name: Log in to Azure
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     # Get AKS credentials
  #     - name: Get AKS credentials
  #       run: |
  #         az aks get-credentials --resource-group RGroup --name RGroup-aks

  #     # Install Helm
  #     - name: Install Helm
  #       run: |
  #         curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  #     # Deploy the Node.js application using Helm
  #     - name: Deploy Node.js app to AKS
  #       run: |
  #         helm upgrade --install sample-nodejs ./helm-charts \
  #           --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/sample-nodejs \
  #           --set image.tag=latest
